# Generated by Django 4.1.5 on 2023-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_profile_pic_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='ba9fd6137076385.Y3JvcCwzNzY3LDI5NDcsMCwyNzk.jpg', null=True, upload_to=''),
        ),
    ]
